FROM node:20-alpine

WORKDIR /usr/src/app

# Copy only dependency files first (better caching)
COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm ci

# Generate Prisma client (must use npm script)
RUN npm run db:generate

# Build (you can scope later if using turborepo)
RUN npm run build

CMD ["npm", "run", "start-user-app"]